[custom]
;不要随意改变关键字，否则会导致出错
;acl4SSR规则-在线更新版

;去广告：支持
;自动测速：支持
;微软分流：支持
;苹果分流：支持
;增强中国IP段：不支持
;增强国外GFW：不支持
;多国家分组：支持港/日/美

clash_proxies_style=block
add_emoji=false

ruleset=Ai,https://raw.githubusercontent.com/zzzqqiu/rules/refs/heads/main/ai1.list
ruleset=reject,https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/reject.txt
ruleset=icloud,https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/icloud.txt
ruleset=apple,https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/apple.txt
ruleset=google,https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/google.txt
ruleset=proxy,https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/proxy.txt
ruleset=direct,https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/direct.txt
ruleset=private,https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/private.txt
ruleset=gfw,https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/gfw.txt
ruleset=tld-not-cn,https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/tld-not-cn.txt
ruleset=telegramcidr,https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/telegramcidr.txt
ruleset=cncidr,https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/cncidr.txt
ruleset=lancidr,https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/lancidr.txt
ruleset=applications,https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/applications.txt
ruleset=LAN,[]GEOIP,LAN
ruleset=CN,[]GEOIP,CN
ruleset=FINAL,[]FINAL

custom_proxy_group=PROXY`select`.*`[]DIRECT
custom_proxy_group=Ai`select`[]PROXY`[]DIRECT
custom_proxy_group=reject`select`[]REJECT`[]DIRECT
custom_proxy_group=icloud`select`[]DIRECT`[]PROXY
custom_proxy_group=apple`select`[]DIRECT`[]PROXY
custom_proxy_group=google`select`[]PROXY`[]DIRECT
custom_proxy_group=proxy`select`[]PROXY`[]DIRECT
custom_proxy_group=direct`select`[]DIRECT`[]PROXY
custom_proxy_group=private`select`[]DIRECT`[]PROXY
custom_proxy_group=gfw`select`[]PROXY`[]DIRECT
custom_proxy_group=tld-not-cn`select`[]PROXY`[]DIRECT
custom_proxy_group=telegramcidr`select`[]PROXY`[]DIRECT
custom_proxy_group=cncidr`select`[]DIRECT`[]PROXY
custom_proxy_group=lancidr`select`[]DIRECT`[]PROXY
custom_proxy_group=applications`select`[]DIRECT`[]PROXY
custom_proxy_group=LAN`select`[]DIRECT`[]PROXY
custom_proxy_group=CN`select`[]DIRECT`[]PROXY
custom_proxy_group=FINAL`select`[]PROXY`[]DIRECT

;custom_proxy_group=🇭🇰 香港节点`select`(港|HK|hk|Hong Kong|HongKong|hongkong|HKG)`http://www.gstatic.com/generate_204`300,,50
;custom_proxy_group=🇯🇵 日本节点`select`(日本|川日|东京|大阪|泉日|埼玉|沪日|深日|[^-]日|JP|Japan)`http://www.gstatic.com/generate_204`300,,50
;custom_proxy_group=🇺🇲 美国节点`select`(美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States|ATL|BUF|DFW|EWR|IAD|LAX|MCI|MIA|ORD|PHX|PDX|SEA|SJC)`http://www.gstatic.com/generate_204`300,,150

clash_rule_base=https://raw.githubusercontent.com/zzzqqiu/rules/refs/heads/main/general.yaml
enable_rule_generator=true
overwrite_original_rules=true
